root: true
env:
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
  - import
rules:
  import/newline-after-import: ["error", { "count": 2 }]
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
